version: "2"
services:
  chromedriver:
    image: robcherry/docker-chromedriver:latest
    ports:
      - "4444:4444"

  browser:
    build:
      context: .
      dockerfile: "browser.service/Dockerfile"
    links:
      - chromedriver
    depends_on:
      - chromedriver

  retriever:
    build:
      context: .
      dockerfile: "retriever.service/Dockerfile"

  tags:
    build:
      context: .
      dockerfile: "tags.service/Dockerfile"
