version: "3"
services:
  chromedriver:
    image: robcherry/docker-chromedriver:latest
    ports:
      - "4444:4444"

  browser:
    build:
      context: .
      dockerfile: "services/browser/Dockerfile"
    links:
      - chromedriver
    depends_on:
      - chromedriver

  retriever:
    build:
      context: .
      dockerfile: "services/retriever/Dockerfile"

  tags:
    build:
      context: .
      dockerfile: "services/tags/Dockerfile"
